package com.psc.elekha.dto

import kotlinx.serialization.Serializable

@Serializable
data class CustomerUploadDTO(
    val GUID: String,
    val CustomerID: String? = null,
    val CustomerTypeID: Int? = null,
    val UserID: String? = null,
    val LivingStatusID: Int? = null,
    val MaritalStatusID: Int? = null,
    val FirstName: String? = null,
    val MiddleName: String? = null,
    val LastName: String? = null,
    val CustomerImage: String? = null,

    val HusbandFName: String? = null,
    val HusbandMName: String? = null,
    val HusbandLName: String? = null,

    val GuarantorID: Int? = null,
    val GurantorFName: String? = null,
    val GurantorMName: String? = null,
    val GurantorLName: String? = null,
    val GuarantorImage: String? = null,
    val GuarantorDOB: String? = null,
    val GurantorAge: Int? = null,
    val GurarantorMobileNo: String? = null,
    val IsMobileNoValidatedGuarantor: Boolean? = null,
    val GurantorKElectricNumber: String? = null,

    val DOB: String? = null,
    val AgeAsOnYear: Int? = null,
    val Age: Int? = null,
    val ContactNoOwner: Int? = null,
    val ContactNo: String? = null,
    val PhoneNo: String? = null,

    val ReligionID: Int? = null,
    val CasteID: Int? = null,
    val EducationID: Int? = null,
    val OccuptionID: Int? = null,
    val MonthlyIncomeID: Int? = null,
    val LoanPurposeID: Int? = null,

    val HouseNo: String? = null,
    val PlotNo: String? = null,
    val Gali: String? = null,
    val Mohalla: String? = null,
    val Road: String? = null,
    val VillageID: Int? = null,
    val City: String? = null,
    val PinCode: String? = null,
    val StateID: Int? = null,
    val DistrictID: Int? = null,
    val Tehsil: String? = null,
    val Landmark: String? = null,
    val Address: String? = null,

    val MaternalAddress: String? = null,
    val MaternalMobileNo: String? = null,
    val MaternalStateID: Int? = null,
    val MaternalVillageName: String? = null,
    val MaternalFatherName: String? = null,

    val Assets_HouseEvaluation: Int? = null,
    val Assets_HouseStatus: Int? = null,
    val Assets_CeilingStatus: Int? = null,
    val Assets_Wall: Int? = null,
    val Assets_Rooms: Int? = null,
    val Assets_Electricity: Int? = null,
    val Assets_WaterSupply: Int? = null,
    val Assets_Sanitation: Int? = null,
    val Assets_LandHolding: Int? = null,

    val Assets_Animal_Cow: Boolean? = null,
    val Assets_Animal_Cow_Quantity: Int? = null,
    val Assets_Animal_Buffalo: Boolean? = null,
    val Assets_Animal_Buffalo_Quantity: Int? = null,
    val Assets_Animal_Goat: Boolean? = null,
    val Assets_Animal_Goat_Quantity: Int? = null,
    val Assets_Animal_Sheep: Boolean? = null,
    val Assets_Animal_Sheep_Quantity: Int? = null,
    val Assets_Animal_Other: Boolean? = null,
    val Assets_Animal_Other_Quantity: Int? = null,

    val Assets_Other_Television: Boolean? = null,
    val Assets_Other_Refrigerator: Boolean? = null,
    val Assets_Other_WaterCooler: Boolean? = null,
    val Assets_Other_WashingMachine: Boolean? = null,
    val Assets_Other_Sofa: Boolean? = null,
    val Assets_Other_Gas: Int? = null,

    val Assets_AddVehicle: Int? = null,
    val Assets_AddVehicle_Quantity: Int? = null,
    val Assets_PrimaryVehicle: Int? = null,
    val Assets_PrimaryVehicle_Quantity: Int? = null,

    val TotalMFI: Int? = null,
    val ToatalActiveMFI: Int? = null,
    val DisbursedAmtMFI: Int? = null,
    val LoanMFIOutstandingSelf: Int? = null,
    val LoanMFIOutstandingCreditEnquiry: Int? = null,
    val CreditEnquiryRemarks: String? = null,

    val PovertyStatus: String? = null,
    val KYCStatus: String? = null,

    val CGTMarks: Int? = null,
    val GRTDate: String? = null,
    val GRTPlace: String? = null,
    val GRTLat: String? = null,
    val GRTLong: String? = null,

    val RegistrationStatusID: Int? = null,
    val RegistrationDate: String? = null,
    val RegPlace: String? = null,
    val RegLat: String? = null,
    val RegLong: String? = null,

    val LoanAppliedID: Int? = null,
    val LoanApprovedID: Int? = null,
    val LoanApprovalDate: String? = null,
    val LoanApprovedAmt: Int? = null,
    val LoanApprovedInterestRate: Double? = null,
    val LoanApprovedInsuranceAmt: Int? = null,
    val LoanApprovedFeesAmt: Int? = null,
    val LoanApprovedInstallmentAmt: Int? = null,
    val LoanApprovedPaymentWeeks: Int? = null,
    val LoanApprovedCloserMinWeeks: Int? = null,
    val LoanApprovedRemarks: String? = null,

    val LoanSanctionedID: Int? = null,
    val LoanDisbursedID: Int? = null,
    val LoanDisbursedDate: String? = null,
    val LoanDisbRemarks: String? = null,
    val LoanEMIDate: String? = null,
    val LoanChequeBankID: Int? = null,
    val LoanChequeNo: String? = null,

    val IsLoanClosed: Boolean? = null,
    val IsWriteOff: Boolean? = null,
    val LoanCycle: Int? = null,

    val TabletID: String? = null,
    val TabletVersionName: String? = null,
    val FundSourceID: Int? = null,

    val DailyExpense: Int? = null,
    val MedicalExpense: Int? = null,
    val EducationExpense: Int? = null,
    val OtherExpense: Int? = null,
    val TotalMonthlyExpenditure: Int? = null,
    val TotalAnnualExpenditure: Int? = null,
    val FamilyMonthlyIncome: Int? = null,

    val Duplicate_Customer_Remark: String? = null,
    val Remarks: String? = null,

    val IsOldCustomer: Boolean? = null,
    val CustomerNickName: String? = null,
    val IsMobileNoValidated: Boolean? = null,

    val CreatedBy: String? = null,
    val CreatedOn: String? = null,
    val UpdatedBy: String? = null,
    val UpdatedOn: String? = null,
    val UploadedOn: String? = null,
    val IsDeleted: Boolean? = null,
    val IsEdited: Int? = null,
    val IsUpload: Int? = null,
    val OTPCODE: String? = null,

    val CKYC_UID: String? = null,
    val CKYC_UID_Image: String? = null,
    val CKYC_UID_Image2: String? = null,
    val CKYC_VoterCard: String? = null,
    val CKYC_VoterCard_Image: String? = null,
    val CKYC_VoterCard_Image2: String? = null,
    val CKYC_Passport: String? = null,
    val CKYC_Passport_Image: String? = null,
    val CKYC_Passport_Image2: String? = null,
    val CKYC_DL: String? = null,
    val CKYC_DL_Image: String? = null,
    val CKYC_PANCard: String? = null,
    val CKYC_PANCard_Image: String? = null,
    val CKYC_Pancard_Name: String? = null,
    val CKYC_OtherID: String? = null,
    val CKYC_OtherID_Image: String? = null,
    val CKYC_ElectricityBill: String? = null,
    val CKYC_ElectricityBillRelationID: Int? = null,
    val CKYC_ElectricityBill_Image: String? = null,
    val CKYC_ElectricityBill_Name: String? = null,
    val CKYC_WaterBill: String? = null,
    val CKYC_WaterBillRelationID: Int? = null,
    val CKYC_WaterBill_Image: String? = null,
    val CKYC_WaterBill_Name: String? = null,
    val CKYC_JobCard: String? = null,
    val CKYC_JobCardRelationID: Int? = null,
    val CKYC_JobCard_Image: String? = null,
    val CKYC_JobCard_Image2: String? = null,
    val CKYC_JobCard_Name: String? = null,
    val CKYC_OtherAP: String? = null,
    val CKYC_OtherAP_RelationID: Int? = null,
    val CKYC_OtherAP_Image: String? = null,
    val CKYC_OtherAP_Name: String? = null,
    val CKYC_RationCard: String? = null,
    val CKYC_RationCard_Image: String? = null,
    val CKYC_RationCard_Image2: String? = null,
    val CKYC_Bank: Int? = null,
    val CKYC_BankAccountNumber: String? = null,
    val CKYC_Bank_Image: String? = null,
    val CKYC_Bank_Branch: String? = null,
    val CKYC_Aadhar_Name: String? = null,
    val CKYC_VoterId_Name: String? = null,
    val GKYC_UID: String? = null,
    val GKYC_UID_Image: String? = null,
    val GKYC_UID_Image2: String? = null,
    val GKYC_VoterCard: String? = null,
    val GKYC_VoterCard_Image: String? = null,
    val GKYC_VoterCard_Image2: String? = null,
    val GKYC_Passport: String? = null,
    val GKYC_Passport_Image: String? = null,
    val GKYC_Passport_Image2: String? = null,
    val GKYC_DL: String? = null,
    val GKYC_DL_Image: String? = null,
    val GKYC_PANCard: String? = null,
    val GKYC_PANCard_Image: String? = null,
    val GKYC_Pancard_Name: String? = null,
    val GKYC_OtherID: String? = null,
    val GKYC_OtherID_Image: String? = null,
    val GKYC_OtherID_Image2: String? = null,
    val GKYC_ElectricityBill: String? = null,
    val GKYC_ElectricityBillRelationID: Int? = null,
    val GKYC_ElectricityBill_Image: String? = null,
    val GKYC_ElectricityBill_Name: String? = null,
    val GKYC_WaterBill: String? = null,
    val GKYC_WaterBilRelationID: Int? = null,
    val GKYC_WaterBill_Image: String? = null,
    val GKYC_WaterBill_Name: String? = null,
    val GKYC_JobCard: String? = null,
    val GKYC_JobCardRelationID: Int? = null,
    val GKYC_JobCard_Image: String? = null,
    val GKYC_JobCard_Image2: String? = null,
    val GKYC_JobCard_Name: String? = null,
    val GKYC_OtherAP: String? = null,
    val GKYC_OtherAP_RelationID: Int? = null,
    val GKYC_OtherAP_Image: String? = null,
    val GKYC_OtherAP_Name: String? = null,
    val GKYC_RationCard: String? = null,
    val GKYC_RationCard_Image: String? = null,
    val GKYC_Bank: Int? = null,
    val GKYC_BankAccountNumber: String? = null,
    val GKYC_Bank_Image: String? = null,
    val GKYC_IFSCCode: String? = null,
    val GKYC_BankNameEditable: String? = null,

    val CutomerStatusID: Int? = null,
    val LoanApprovalDoneBy: String? = null,
    val LoanDisbursalDoneBy: String? = null,
    val GRTDoneBy: String? = null,
    val CreditEnquiryDoneBy: String? = null,
    val CGTDoneBy: String? = null,
    val ExistingLoanAmount: Int? = null,
    val ExistingLoanCurrentOutstanding: Int? = null,
    val ExistingLoanCurrentWeek: Int? = null,
    val HouseHoldAssesment_Image: String? = null
)
